version = 1

exclude_patterns = [
  "config/**",
  "test/**"
]

test_patterns = [
  "test/**"
]

[[analyzers]]
name = "docker"
enabled = true
  [analyzers.meta]
  dockerfile_paths = [".docker/Dockerfile"]

[[analyzers]]
name = "python"
enabled = true
dependency_file_paths = [
  "requirements/prod.txt",
  "requirements/test.txt"
]
  [analyzers.meta]
  runtime_version = "3.x.x"
  max_line_length = 88

[[analyzers]]
name = "secrets"
enabled = true

[[analyzers]]
name = "shell"
enabled = true
  [analyzers.meta]
  dialect = "bash"

[[analyzers]]
name = "test-coverage"
enabled = true
