version: "3.8"


networks:
    backend:
        name: backend


services:
    backend:
        image: backend:development
        build:
            context: .
            dockerfile: .docker/Dockerfile
        networks:
            - backend
        ports:
            - 8000:8000
        volumes:
            - .:/usr/src/app
