version: "3.8"


networks:
    backend:
        name: backend


services:
    backend:
        image: backend:development
        command: uvicorn --factory --host 0.0.0.0 --port 8000 --reload --log-config config/log_config.json --access-log --loop uvloop --http httptools --ws none src.app:create_app
        build:
            context: .
            dockerfile: .docker/Dockerfile
        networks:
            - backend
        ports:
            - 8000:8000
        volumes:
            - .:/usr/src/app
