version: "3.8"


networks:
    backend:
        name: backend


services:
    backend:
        image: backend:development
        command: uvicorn --factory --host 0.0.0.0 --port 8000 --reload --access-log --loop uvloop --http httptools --ws none src.app:create_app
        build:
            context: .
            dockerfile: .docker/Dockerfile
        env_file:
            - .env
        networks:
            - backend
        ports:
            - 8000:8000
        volumes:
            - .:/usr/src/app

    postgres:
        image: postgres:13.3-alpine
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: postgres
        networks:
            - backend
        volumes:
            - gambley_data:/var/lib/postgresql/data


volumes:
    gambley_data:
        name: gambley_data
